name: Tests
on:
  push:
      branches:
          - main
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

env:
  UPSTASH_REDIS_REST_URL2: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN2: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
  UPSTASH_REDIS_REST_URL: foobar
  UPSTASH_REDIS_REST_TOKEN: secret-token
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: test

    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install bun
        run:     curl -fsSL https://bun.sh/install | bash
      - name: Install dependencies
        run: ~/.bun/bin/bun install
        
      - name: Run tests
        run: ~/.bun/bin/bun test --coverage
      
      - name: Build
        run: ~/.bun/bin/bun run build

  
